### ISSUE TITLE
Add Ability to Prepare with Custom State

### ISSUE THREAD

**Issue by Calidus** [IdentityModel/IdentityModel.OidcClient2#339]
I would like to have the ability to pass a custom state object into `PrepareLoginAsync`. Its a rather small change that can be non breaking by using default parameters. Is this a PR the project would be interested in?

**Comment by leastprivilege** [comment]
Hi, 

OK - please make a proposal as a PR. 

Out of curiosity - why?

**Comment by Calidus** [comment]
We use PKCE so we don't need state to give us CSRF protection so we're passing application state instead.

**Comment by leastprivilege** [comment]
..and you are protecting that state somehow?

**Comment by leastprivilege** [comment]
Also - you are in a native (aka stateful) app - why do you want to manage state by round-tripping it to the server?

**Comment by Calidus** [comment]
> ..and you are protecting that state somehow?

We protect the state by passing a cryptographic hash as part of the state data just as the library is doing. Would renaming the `customState` parameter to `encryptedCustomState` make that more clear?

> Also - you are in a native (aka stateful) app - why do you want to manage state by round-tripping it to the server?

For analytics and compatibility, want to pass information from our native app to our auth server.

**Comment by leastprivilege** [comment]
So why don't you then simply use a custom parameter here

https://github.com/IdentityModel/IdentityModel.OidcClient/blob/main/src/OidcClient/OidcClient.cs#L107

?

**Comment by Calidus** [comment]
I think that will work! I didn't know that was a option. The typed frontParameters is much more clean than the older extraParamters `object'.
